In [ ]:
#Backward Difference and h_opt

In [ ]:
#Second derivatives and Interpolation

In [2]:
import numpy as np
from math import exp,sin,cos,log10

In [3]:
def f(x):
    return exp(sin(2*x))

def fprime(x):
    return 2*exp(sin(2*x))*cos(2*x)

def calc_fd(f,x,h): #Forward Difference
    fd=(f(x+h)-f(x))/h
    return fd

def calc_cd(f,x,h): #Central Difference and h_opt
    cd=(f(x+h/2)-f(x-h/2))/h
    return cd

x=0.5
an=fprime(x)

hs=[10**(-i) for i in range(1,12)]
fds=[abs(calc_fd(f,x,h)-an)for h in hs]
cds=[abs(calc_cd(f,x,h)-an)for h in hs]

rowf="{0:1.0e}   {1:1.16f}   {2:1.16f}"
print("h    abs.error in fd    abs.error in cd")
for i in range(len(hs)):
    print(rowf.format(hs[i],fds[i],cds[i]))

h    abs.error in fd    abs.error in cd
1e-01   0.3077044583376249   0.0134656094697734
1e-02   0.0260359156900742   0.0001350472493096
1e-03   0.0025550421497806   0.0000013505120728
1e-04   0.0002550180941236   0.0000000135077878
1e-05   0.0000254969542519   0.0000000001495843
1e-06   0.0000025492660578   0.0000000002500959
1e-07   0.0000002564334673   0.0000000011382744
1e-08   0.0000000189018428   0.0000000189018428
1e-09   0.0000003741732106   0.0000000699159992
1e-10   0.0000021505300500   0.0000021505300500
1e-11   0.0000332367747395   0.0000111721462455


In [6]:
#Suppose you have a numpy array
x=np.linspace(1,10,10)
print(x)

#I can move all values to the left/right using roll
x_roll=np.roll(x,1) #change 1 to -1. what happens? 
print(x_roll)

#then I could exploit array operations to get their difference
x_diff=x_roll-x
print(x_diff)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[10.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[ 9. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
